### PR TITLE
Development

### PR DESCRIPTION
**Pull request by KfWelch**

### CODE REVIEW

**Comment by connellrobert** [comment]
decrease code smells in sonarcloud

**Comment by connellrobert** [comment]
take care of security vulnerability in sonarcloud

**Comment by connellrobert** [comment]
too much commented out code in the email controller

**Comment by connellrobert** [comment]
compiler error in the demoApplicationTest class due to package name.

**Comment by connellrobert** [comment]
empty test method in DemoApplicationTest.java

**Comment by maresh315** [comment]
closing pull request

**Pull request closed without merging**
